version: "2"
services:
  bibcat:
    build: .
    ports:
        - "5000:5000"
    network:
     - new

  semanticServer:
    image: knowledgelinks/semantic-server
    ports:
     - "8080:8080"
     - "9999:9999"
     - "9200:9200"
    volumes:
     - /opt/bibcat_repository/fedora-data:/usr/share/fedora-data
     - /opt/bibcat_triplestore:/usr/share/blazegraph
     - $HOME/local_data:/local_data
    network:
     - new

  web:
    build: .
    dockerfile: DockerNginx
    networks:
     - new
    ports:
     - "80:80"
     - "443:443"

networks:
  - new:
