version: "2"
services:
  bibcat:
    build: 
      context: .
    ports:
      - "5000:5000"
    networks:
      - new

  semantic_server:
    image: knowledgelinks/semantic-server
    ports:
      - "8080:8080"
      - "9999:9999"
      - "9200:9200"
    volumes:
      - /opt/bibcat_repository/fedora-data:/usr/share/fedora-data
      - /opt/bibcat_triplestore:/usr/share/blazegraph
      - $HOME/local_data:/local_data
    networks:
      - new

  web:
    build: 
      context: .
      dockerfile: DockerNginx
    networks:
      - new
    ports:
      - "80:80"
      - "443:443"

networks:
  new:
